### ISSUE TITLE
Lidar passes through walls at close range

### ISSUE THREAD

**Issue by M1chaelM** [Field-Robotics-Lab/nps_uw_sensors_gazebo#12]
To simulate the 3D-at-depth SL3 specs, the underwater lidar is set with a minimum range of 1 meter. This appears to produce the unintended side-effect of having the lidar rays pass through objects that are closer than this minimum range:

![lidar_ghost](https://user-images.githubusercontent.com/8611855/90177557-93d40a00-dd5f-11ea-9730-22b92fd7e8c0.png)

The desired behavior would be for these rays to be blocked. Note that the point cloud for these objects is represented in fuschia in rviz, which may indicate that we are actually getting the desired behavior (i.e. these points are not part of the "real" sensor output and are are only being represented for debugging purposes). In that case, it may be that the only problem is the visualization of the rays, and this is a bug in Gazebo.

What we need to know:
* Is the rostopic output of the point cloud correct (i.e. does it exclude the points that are closer than the minimum range)?
* Is the rviz visualization the expected behavior?
* Is the Gazebo ray visualization the expected behavior?
* Is there some better way to implement the minimum range to get the behavior we want (if we are actually not getting it)?

**Comment by BruceMty** [comment]
I'm fine with the existing Gazebo ray visualization now that I understand that these rays begin starting at 1 meter.  Although the manufacturer's specifications indicate a minimum range, we may wish to set the minimum range in our model to, e.g. 0.1 meter in order to avoid this artifact.

**Comment by M1chaelM** [comment]
Just to make sure we're reading this right, I verified that placing a wall between the lidar and the target has no affect on the number of points reported or their intensities when the wall is within the minimum range. That is, the following two scenes produce the same output:

## With a wall
![Screenshot from 2021-02-09 16-53-34](https://user-images.githubusercontent.com/8611855/107449685-dc933280-6af8-11eb-8df4-a349197cc4c5.png)

## With no wall
![Screenshot from 2021-02-09 17-03-05](https://user-images.githubusercontent.com/8611855/107449688-df8e2300-6af8-11eb-8f66-d2cdaaeab60b.png)

Obviously, this is not ideal. A possible fix would be to shrink the minimum beam length and discard points that are too close using a software filter, but this would have to happen when parsing the topic. A better fix would be to add a parameter to the lidar sensor itself that distinguishes between the range at which the beam is intended to start (used to prevent it from colliding with the  object the sensor is mounted on) and the minimum range at which we expect to receive useful data.

**Comment by M1chaelM** [comment]
I think this would be a feature request for the maintainers of the `ros_velodyne_gpu_laser` plugin, which we adapted. Since developing the underwater lidar is not currently a top priority, I am closing this for now, and I will leave a note in Trello to discuss a potential feature request.
