### ISSUE TITLE
Clarifying meaning of sonar ray angles

### ISSUE THREAD

**Issue by M1chaelM** [Field-Robotics-Lab/nps_uw_sensors_gazebo#14]
The (crude) diagram below shows one possible interpretation of the elevation and azimuth angles corresponding to individual sonar rays. The coordinate frame matches the normal vector values returned from the depth camera:

- The 'x' axis is horizontal.
- The 'y' axis is vertical and inverted so increasing values moves from top to bottom.
- The 'z' axis corresponds to depth from the perspective of the sensor.

The elevation and azimuth angles are a new thing we are introducing. In the interpretation suggested here, increasing angles corresponds to counterclockwise rotation. 

<img width="632" alt="Screen Shot 2020-08-28 at 5 12 06 PM" src="https://user-images.githubusercontent.com/8611855/91623766-a8b0c000-e951-11ea-966c-ff0a0b9b9e60.png">

Examples:

|elevation   |azimuth   |direction vector   |
|---|---|---|
|  0 | 0   |<0,0,1>   |
| 0  |pi/2   | <1,0,0>  |
|  0 | -pi/2  |  <-1,0,0> |
| pi/2  | 0  | <0,-1,0>  |
| -pi/2  | 0  | <0, 1,0>  |

**Comment by woensug-choi** [comment]
- Azimuthal angle
[azimutal angle reference image](http://www.teledynemarine.com/blog/First-images-from-the-new-RESON-SeaBat-F50)
   - portside -pi/2, starboard pi/2, forward 0
- Elevation angle
[elevation angle reference image](https://journals.plos.org/plosone/article/figure?id=10.1371/journal.pone.0146396.g005)
   - forward 0, downward pi/2

While I'm not used to azimuthal angle definition, the elevation definition with pi/2 looking down and 0 looking forward is something I am familiar with.

I suspect the depth camera uses same coordinate system when hearing that the downward looking is positive for normal vectors. Maybe the zero horizontal also represented Y (in gazebo, portside if x is considered ahead) direction?
If so,

% calculates a direction vector for the ray
def ray_angles_to_vector(azimuth, elevation):
x = cos(azimuth)*cos(-elevation)
y = sin(azimuth)*cos(-elevation)
z = sin(-elevation)
return np.array([x,y,z])

% takes two numpy arrays and returns the angle of incidence between them in radians
def get_incidence(ray_vector, normal_vector):
return pi - acos(ray_vector.dot(normal_vector))

% main code
alpha = get_incidence(ray_angles_to_vector(ray.azimuthAngle,ray.elevationAngle),ray_angles_to_vector(depthCameraObtainedNormal[1],depthCameraObtainedNormal[2]))

What do you think?

**Comment by M1chaelM** [comment]
OK regarding the angles, let's follow the conventions @woensug-choi proposes. One clarification regarding elevation angle--this will mean:

### Elevation angle
* forward 0
* downward pi/2
* **upward -pi/2**

Can you confirm? The upward is missing in your version so I want to be sure.

**Comment by M1chaelM** [comment]
Regarding the vectors, the function you've given has elevation corresponding to the z axis. I think this is more natural but, again, it is not what the depth camera does. In order for the incidence angle equation to work correctly, we'll need both the` ray_vector` and the `normal_vector` to use the same axis labels.

I think it would be nice if our plugin's behavior matched what one would expect from using the GPURay sensor and the usually object coordinate frames in Gazebo. I'm going to do some tests to verify these and propose a complimentary approach. This may mean we translate the normals returned by the depth camera into a more intuitive direction vector.

**Comment by M1chaelM** [comment]
After some further testing of the GPURay sensor, I think the right thing to do is keep my original proposal of having positive angles correspond with counterclockwise rotation, as this is consistent with the behavior of the GPURay.

Here is a screenshot of rays coming from a lidar device where the horizontal FOV has been set to extend from 0 to 30 degrees:
![GPURay_horizontal_min_0_max_30](https://user-images.githubusercontent.com/8611855/91781087-499bb700-ebae-11ea-8a79-8c53ba3e2362.png)

Here is a screenshot of rays where the vertical FOV is set from -30 to 0 degrees. Note that a negative angle points down in this case.

![GPURay_vertical_min_-30_max_0](https://user-images.githubusercontent.com/8611855/91781229-a008f580-ebae-11ea-8b09-2730d5410e5a.png)

Unless there is a compelling reason to deviate, let's stick with this convention.

**Comment by M1chaelM** [comment]
In order to confirm the standard coordinates in Gazebo, I used the GUI to visualize forces applied to the tank in the standalone demos. The results were as follows:
* **x axis**: negative values indicate port, positive starboard
* **y axis**: negative is backward (stern), positive forward (bow)
* **z axis**: negative is down, positive up

Here screenshots for confirmation:
#### x direction
![x_pos](https://user-images.githubusercontent.com/8611855/91781656-ac418280-ebaf-11ea-9972-6c44c39c7fd9.png)

#### y direction
![y_pos](https://user-images.githubusercontent.com/8611855/91781664-b06da000-ebaf-11ea-9d83-6a9712bf0c8d.png)

#### z direction
![z_pos](https://user-images.githubusercontent.com/8611855/91781687-c0857f80-ebaf-11ea-9099-474a483821cd.png)

**Comment by woensug-choi** [comment]
Thank you for confirming! I agree with the idea that we stick to gazebo's and Depth camera sensor's conventions since sonar conventions can be changed easily at this stage.

## To summarize,
### Cartesian coordinate (XYZ)
* **x axis**: negative is backward (stern), positive forward (bow)
* **y axis**: negative values indicate port, positive starboard
* **z axis**: negative is down, positive up
### Horizontal (Azimuthal) - Vertical (Elevation)
* **Horizontal axis**: positive values indicate port, negative starboard
* **Vertical axis**: positive looking up, negative looking down

## To calculate alpha (incident angle)
% calculates a direction vector for the ray
def ray_angles_to_vector(azimuth, elevation):
x = cos(-azimuth)*cos(elevation)
y = sin(-azimuth)*cos(elevation)
z = sin(elevation)
return np.array([x,y,z])

% takes two numpy arrays and returns the angle of incidence between them in radians
def get_incidence(ray_vector, normal_vector):
return pi - acos(ray_vector.dot(normal_vector))

% main code
alpha = get_incidence(ray_angles_to_vector(ray.azimuthAngle,ray.elevationAngle),ray_angles_to_vector(depthCameraObtainedNormal[1],depthCameraObtainedNormal[2]))

**Comment by M1chaelM** [comment]
Great! I think we are converging, but not quite there. If we use the Cartesian axes you propose, we have to alter the direction vectors returned from the depth camera to match them. Something like:

``` python3
# changes normals from depth camera to match our axis choices
def fix_normal(depth_normal):
    x,y,z = depth_normal
    return np.array([z, x, -y])

# calculates a direction vector for the ray
def ray_angles_to_vector(azimuth, elevation):
    x = cos(-azimuth)*cos(elevation)
    y = sin(-azimuth)*cos(elevation)
    z = sin(elevation)
    return np.array([x,y,z])

# takes two numpy arrays and returns the angle of incidence between them in radians
def get_incidence(ray_vector, normal_vector):
    return pi - acos(ray_vector.dot(normal_vector))

# main
# set ray.azimuth and ray.elevation from user specified configuration
# get ray.range, ray.normal, ray.sonar_retro corresponding to the ray using Gazebo's depth camera.
ray_vector = ray_angles_to_vector(ray.azimuth,ray.elevation)
normal_vector = fix_normal(ray.normal)
alpha = get_incidence(ray_vector, normal_vector)
```

Alternatively, we could just keep the depth camera axes and make our axes match theirs. In that case we would use:

``` python3
# calculates a direction vector for the ray
def ray_angles_to_vector(azimuth, elevation):
    x = sin(-azimuth)*cos(elevation)
    y = sin(-elevation)
    z = cos(azimuth)*cos(elevation)
    return np.array([x,y,z])

# takes two numpy arrays and returns the angle of incidence between them in radians
def get_incidence(ray_vector, normal_vector):
    return pi - acos(ray_vector.dot(normal_vector))

# main
# set ray.azimuth and ray.elevation from user specified configuration
# get ray.range, ray.normal, ray.sonar_retro corresponding to the ray using Gazebo's depth camera.
ray_vector = ray_angles_to_vector(ray.azimuth,ray.elevation)
alpha = get_incidence(ray_vector, ray.normal)
```
The second version is slightly weirder because the depth camera vectors are weird. I think they are equivalent and I'm fine with either one. @BruceMty do you have a preference?

**Comment by M1chaelM** [comment]
@mabelzhang suggests the first version, in which we translate camera coordinates to the robot coordinates in the world.

**Comment by M1chaelM** [comment]
Following discussion in the meeting this morning, we need to make a minor adjustment so positive values along the y axis go to port rather than starboard for consistency with the right hand rule.

Here is the final summary:

## Cartesian coordinate (XYZ)
* **x axis**: negative is backward (stern), positive forward (bow)
* **y axis**: negative values indicate starboard, positive port
* **z axis**: negative is down, positive up

## Ray Angles
* **Horizontal (Azimuth)**: positive values indicate port, negative starboard
* **Vertical (Elevation)**: positive looking up, negative looking down

## To calculate alpha (incident angle)
``` python3
# changes normals from depth camera to match our axis choices
def fix_normal(depth_normal):
    x,y,z = depth_normal
    return np.array([z, -x, -y])

# calculates a direction vector for the ray
def ray_angles_to_vector(azimuth, elevation):
    x = cos(azimuth)*cos(elevation)
    y = sin(azimuth)*cos(elevation)
    z = sin(elevation)
    return np.array([x,y,z])

# takes two numpy arrays and returns the angle of incidence between them in radians
def get_incidence(ray_vector, normal_vector):
    return pi - acos(ray_vector.dot(normal_vector))

# main
# set ray.azimuth and ray.elevation from user specified configuration
# get ray.range, ray.normal, ray.sonar_retro corresponding to the ray using Gazebo's depth camera.
ray_vector = ray_angles_to_vector(ray.azimuth,ray.elevation)
normal_vector = fix_normal(ray.normal)
alpha = get_incidence(ray_vector, normal_vector)
```

@BruceMty Please use the above functions to calculate the angle of incidence. Thank you!

**Comment by M1chaelM** [comment]
It appears ROS has a standard convention that I was not aware of, written here: https://www.ros.org/reps/rep-0103.html#coordinate-frame-conventions

Happily, it matches the solution we eventually converged on.
