### ISSUE TITLE
Sonar beam computation is slow

### ISSUE THREAD

**Issue by BruceMty** [Field-Robotics-Lab/nps_uw_sensors_gazebo#18]
The python implementation of the sonar model runs very slowly. https://github.com/Field-Robotics-Lab/dave/wiki/Depth-Camera-Sonar-with-Normals reports that it takes ~10s to generate a sonar scan for a scenario with a reduced number of rays/beams.

The computational burden in this implementation is the point scattering model, which is a very important part of our current sonar model.  In addition to porting this to C++, we will want to consider options to improve performance, in particular parallelization.

**Comment by woensug-choi** [comment]
This will be addressed again after adopting the simplified point scattering model and C++ migration with the CUDA core parallelization. https://github.com/Field-Robotics-Lab/nps_uw_sensors_gazebo/issues/21

**Comment by woensug-choi** [comment]
Implementing the CUDA core has shown amazing improvements in calculation time #25. Closing this issue.


***Comparisons (for reference to later developments)***
- Python : ~3000 seconds 
- C++ : ~200 seconds (approx. 150x faster than python)
- CUDA : ~1.5 seconds (approx. 130x faster than C++, 2000 times faster than python)
