### ISSUE TITLE
Python script text format error (not recognizable by the Github)

### ISSUE THREAD

**Issue by woensug-choi** [Field-Robotics-Lab/nps_uw_sensors_gazebo#19]
Getting error msg launching with `roslaunch nps_uw_sensors_gazebo depth_camera_sonar_basic.launch`
```bash
process[depth_and_normals_to_sonar-5]: started with pid [4391]
/usr/bin/env: ‘python\r’: No such file or directory
process[rqt_image_view_image_beams-6]: started with pid [4392]
[depth_and_normals_to_sonar-5] process has died [pid 4391, exit code 127, cmd /home/eric/uuv_ws/src/nps_uw_sensors_gazebo/scripts/sonar_ros.py __name:=depth_and_normals_to_sonar __log:=/home/eric/.ros/log/8a5c2930-fba5-11ea-9dd5-bcee7b8ddb04/depth_and_normals_to_sonar-5.log].
log file: /home/eric/.ros/log/8a5c2930-fba5-11ea-9dd5-bcee7b8ddb04/depth_and_normals_to_sonar-5*.log
```
according to [this thread](https://askubuntu.com/questions/896860/usr-bin-env-python3-r-no-such-file-or-directory)
`The problem are your line ending characters. Your file was created or edited on a Windows system and uses Windows/DOS-style line endings (CR+LF), whereas Linux systems like Ubuntu require Unix-style line endings (LF).`
using package dos2unix with command `dos2unix *.py` fixed the problem which is installed with `sudo apt install dos2unix`. 

_Originally posted by @woensug-choi in https://github.com/Field-Robotics-Lab/nps_uw_sensors_gazebo/pull/13#issuecomment-695862555_

Could not commit the changed python scripts since the Github status says 'No content changes found' but says '3 changed files' at the same time.

**Comment by BruceMty** [comment]
This issue relates to https://github.com/Field-Robotics-Lab/nps_uw_sensors_gazebo/pull/13 which is not merged yet, see discussion there.
