### ISSUE TITLE
Define and implement sonar interfaces

### ISSUE THREAD

**Issue by bsb808** [Field-Robotics-Lab/nps_uw_sensors_gazebo#22]
The output of the simulates sonar sensors is envisioned to be _rare_ data, e.g., acoustic intensity time histories for each beam.  This beam-level data will be delivered via ROS interface and used for visualization, logging, perception processing, etc.   The ROS interface should be consistent with the hardware interfaces, i.e., the simulated sonar should be in the same format as the beam-level data generated by a FLS/MB sonar sensor from typical vendors such as BlueView, Kraken, Klien, etc.

We'll need to define and document the ROS interface and demonstrate connecting the interface with the sonar plugins and with external viewers.  Ideally we could show that the interface can be connected with commercial viewing software through the use of standalone data translation processes.

**Comment by woensug-choi** [comment]
The information provided by Derek, the MCM sensor format specification.
[MCM Sensor HDF Specification v2.1.pdf](https://github.com/Field-Robotics-Lab/nps_uw_sensors_gazebo/files/5399277/MCM.Sensor.HDF.Specification.v2.1.pdf)

**Comment by bsb808** [comment]
Working on creating a ROS interface using this message type:
https://gitlab.com/apl-ocean-engineering/imaging_sonar_msgs

**Comment by bsb808** [comment]
@woensug-choi and @seankrag 
It appears that this is done with commit 86d7391 
Please advise on what is missing.

**Comment by woensug-choi** [comment]
It's all working fine. Closing this issue.
- **Note 1.** The repo is changed to Github one. The msg format is identical. 
   https://github.com/apl-ocean-engineering/acoustic_msgs/blob/main/msg/SonarImage.msg
- **Note 2.** The final result is that the ROS msg exporting from the new sonar plugin is fixed to 8-bit data according to their repo. The bundled viewer is showing better resolution with the 16-bit data feed.

**Comment by seankrag** [comment]
>     * **Note 2.** The final result is that the ROS msg exporting from the new sonar plugin is fixed to 8-bit data according to their repo. The bundled viewer is showing better resolution with the 16-bit data feed.

@woensug-choi Looks good! I believe the SonarImage message format can accommodate 16-bit (or higher) data sizes, using the **data_size** and **is_bigendian** fields to stuff it into the **intensities** array of uint8s. However, we will need to test and verify this functionality before including in a future release.
