### ISSUE TITLE
Consider moving sonar plugin to its own repo

### ISSUE THREAD

**Issue by bsb808** [Field-Robotics-Lab/nps_uw_sensors_gazebo#30]
Given that sonar plugin repo introduces the CUDA dependency, which is likely unique to that plugin, we should consider having a standalone repo.

**Comment by woensug-choi** [comment]
I will be working on this issue for next few weeks. Hope it will get separated before February.

**Comment by woensug-choi** [comment]
PR https://github.com/Field-Robotics-Lab/nps_uw_sensors_gazebo/pull/44 is made for this issue.
