### ISSUE TITLE
Error when dvl sensor attached to whoi gliders

### ISSUE THREAD

**Issue by woensug-choi** [Field-Robotics-Lab/nps_uw_sensors_gazebo#47]
@dtdavi1 I hope this isn't a major sensor plugin type problem, but simply a wrong sensor definition problem. I am still familiarizing myself with SDF/URDF definitions.

I was trying to put whoi_teledyne_whn sensor at the `nps_uw_sensor_gazebo` repository to a glider at https://github.com/Field-Robotics-Lab/glider_hybrid_whoi. I've found an example in the repository and copy-pasted the sensor definitions. I've replaced the code block at the sensor definition xacro file. it did show dvl sensor visually, but the sensor plugin did not load correctly.
```bash
[Err] [SensorManager.cc:333] Unable to create sensor of type[dsros_dvl]
```
```XML
<!-- DVL sensor -->
<!-- <xacro:dvl_plugin_macro
  namespace="${namespace}"
  suffix=""
  parent_link="${namespace}/base_link"
  topic="dvl"
  scale="0.62"
  noise_sigma="0"
  noise_amplitude="0"
  update_rate="7"
  reference_frame="world">
  <origin xyz="0.0 0.0 -0.0825" rpy="0 ${0.5*pi} 0" />
</xacro:dvl_plugin_macro> -->

<xacro:include filename="$(find nps_uw_sensors_gazebo)/urdf/whoi_teledyne_whn.xacro"/>
<xacro:teledyne_whn_macro
  name="dvl" namespace="dvl" xyz="0 0 0"
  dvl_topic="dvl" ranges_topic="ranges"
  robot_link="${namespace}/base_link" joint_xyz="0 0 0"/>
```

If you need a place to test, it's at [dvl_sensor branch](https://github.com/Field-Robotics-Lab/glider_hybrid_whoi/tree/dvl_sensor). You may run with `roslaunch glider_hybrid_whoi_gazebo start_demo_kinematics.launch`

**Comment by dtdavi1** [comment]
@woensug-choi The launch file was missing an argument in the Gazebo launch portion.  The DVL sensor is part of the ds_sim package, so you need to explicitly load the library when Gazebo is started.  I added the line to the start_demo_kinematics.launch file (line 11) and pushed it back up to the repository.

**Comment by woensug-choi** [comment]
@dtdavi1  Thank you! Something that could have taken me much time to figure out!
